# https://github.com/lework/ci-demo-springboot/blob/master/.drone.yml
kind: pipeline
type: docker
name: deploy

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: maven-deploy
    image: maven:3.9.6-eclipse-temurin-21
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: maven-cache
        path: /root/.m2
    commands:
      - unset MAVEN_CONFIG # https://github.com/carlossg/docker-maven/issues/301
      - cd $DRONE_WORKSPACE/framework-dependencies
      - ./mvnw clean deploy -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -U -B
      - cd $DRONE_WORKSPACE/framework-infra
      - ./mvnw clean deploy -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -U -B

# https://docs.drone.io/pipeline/docker/syntax/workspace/
volumes: # 定义流水线挂载目录，用于共享数据# 从宿主机中挂载的目录
  # https://docs.drone.io/pipeline/docker/syntax/volumes/host/
  - name: maven-cache
    host:
      path: /home/sephy/.m2
